---
title: "Variable Creation Outline Paper 1"
author: "Kate Brandt"
date: "January 9, 2019"
output:
  html_document:
    highlight: default
    number_sections: no
    theme: lumen
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
  word_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Last Updated `r format(Sys.Date(), format="%m/%d/%Y")`

# Process to clean and create variables for paper to analyze land cover change and fuel use

**The following is an outline of steps for creating and attaching variables (assigned to Kate and Varun) to LSMS survey clusters for Malawi**

**Scripts and data may be accessed in GISPractice github**

**YEARS Checkoff list**

  2016-17
  
  Merged variables file uploaded to teams - KB 2/20
  
  * ~~MARKET ACCESS~~ (hhgeo_w_calculated_access.rds) KB
  
  * ~~POPULATION DENSITY~~ (hhgeo_w_popden10k.rds) KB
    + Used 2015 AfriPop Data
  
  * ~~ELEVATION~~ (from LSMS)
  
  * ~~SOIL QUALITY~~ (from LSMS)
  
  * ~~ACCESS TO WATER~~ (from LSMS)
  
  * ~~ACCESS TO ELECTRICITY~~ (from LSMS)
  
  * URBAN
  
  2013
  
  Merged variables file uploaded to teams - KB 2/20
  
  * ~~MARKET ACCESS~~ (Completed and uploaded 2/4 - hhgeolonpan_w_calculated_access.rds) KB
  
  * ~~POPULATION DENSITY~~ (Completed and uploaded 2/4 - hhgeolonpan_w_popden10k.rds) KB
    + Used 2010 and 2015 AfriPop Data
    + Created average popden variable for 2013 data points (completed 2/20 - KB)
  
  * ~~ELEVATION~~ (from LSMS)
  
  * ~~SOIL QUALITY~~ (from LSMS)
  
  * ~~ACCESS TO WATER~~ (from LSMS)
  
  * ~~ACCESS TO ELECTRICITY~~ (from LSMS)
  
  * URBAN
  
  2010
  
  Merged variables file uploaded to teams - KB 2/20
  
  * ~~MARKET ACCESS~~ (Completed and uploaded 1/30 - hhgeo10_w_calculated_access.rds) KB
  
  * ~~POPULATION DENSITY~~ (Completed and uploaded 1/30 - hhgeo10_w_popden10k.rds) KB
    + Used 2010 AfriPop Data
  
  * ~~ELEVATION~~ (from LSMS)
  
  * ~~SOIL QUALITY~~ (from LSMS)
  
  * ~~ACCESS TO WATER~~ (from LSMS)
  
  * ~~ACCESS TO ELECTRICITY~~ (from LSMS)
  
  * URBAN
  
  2004 (need to locate geovariables file? 2/4 KB)
  
  * MARKET ACCESS
  
  * POPULATION DENSITY
  
  * ~~ELEVATION~~ (from LSMS)
  
  * ~~SOIL QUALITY~~ (from LSMS)
  
  * ~~ACCESS TO WATER~~ (from LSMS)
  
  * ~~ACCESS TO ELECTRICITY~~ (from LSMS)
  
  * URBAN


# Variable  creation process (described for 2016-17 LSMS set)

# ~~MARKET ACCESS~~ 
  (shortest road distance from an IHS cluster to the nearest city, maybe weighted by night time lights)
  
  * **We need to ask Yu about this.  I don't think that this is the correct way to measure distance to markets using the data that we have?**
  * Ans: We used the Malaria atlas access to cities database which includes road distance [link here](https://map.ox.ac.uk/research-project/accessibility_to_cities/)
  * Variable is a distance unit
  

  **2016-2017 Data**
  
  #~~1 Import LSMS (2016-17) spatial data as .csv~~
  
  #~~2 Created LSMS (2016-17) HH location shapefile~~
    
  * Output: /data/mw16_hh_geo_sp_wgs84 (main file to which variables are added)
    + Script: 01_process_lsms-mw-hh-geo-201617.R
  

  #~~3 Download 'Accessibility to cities (2015)' and create accessibility variable~~
  
  * Downloaded as .tif file
  * Extracted value based on points; added as "access_to_city15_nobuff" variable
  * Extracted mean value within 10km buffer; added as "access_to_city15_buff10k" variable
    + Script: 02_extract_accessibilitytoCities_MW1617.R

  
# POPULATION DENSITY

**Within 10 km buffer of LSMS cluster**

  ~~#1 Download and import AfriPop data for 2015~~
  
  ~~#2 Create density variable using summing buffer values~~
  
  * ~~Sum values for POPULATION of 10 km radius buffer~~
  * Divide sum by area of buffer
  
  
# ~~ELEVATION~~

  #1 Download and import .tif of DEM
  
  #2 Extract DEM value at location point and create variable
  
  * Going to use LSMS variables because they use SRTM
  
# ~~SOIL QUALITY~~
  
  * Not sure how this is going to be captured nor by which data set- need to ask Yu (check Pam data)
  * Checked LSMS variables: using FAO, so we will use those already in LSMS
  
  
# ~~ACCESS TO WATER~~ 

  * Not sure how this is going to be captured nor by which data set- need to ask Yu
  * Should be usable from HH survey questions F38 and F36


# URBAN (Using Night Time Lights) 

  * Not sure how this is going to be captured- need to ask Yu (ask Nick Lam about Masking , urban rural wisconsin data, NOAA urban mapping)
  * ~~Reach out to Dr. Schneider at UWisco~~ (does not have updated data)
  * Process according to global index or regional across SSA?
  




